# Generated by Django 3.2.9 on 2022-03-01 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220301_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='completed',
        ),
    ]
