# Generated by Django 3.2.9 on 2022-03-21 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_emailverification_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_login',
            new_name='temporary_password',
        ),
    ]
