# Generated by Django 3.2.9 on 2022-03-24 21:08

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_auto_20220324_2108'),
        ('users', '0007_auto_20220321_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff person', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(related_name='teachers', to='college.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to=users.models.get_avatar_path, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='phone_number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_publicity',
            field=models.BooleanField(default=True, verbose_name='phone_publicity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='temporary_password',
            field=models.BooleanField(default=True, verbose_name='temporary_password'),
        ),
    ]
