# Generated by Django 3.2.9 on 2022-03-24 21:08

from django.db import migrations, models
import wiki.models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20220222_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlefile',
            name='file',
            field=models.FileField(max_length=255, upload_to=wiki.models.get_file_path),
        ),
    ]
