version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./.env.db
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
    ports:
      - '8000:8000'
    restart: on-failure

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - '80:80'