# Generated by Django 3.2.9 on 2022-02-14 14:40

import college.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220210_2000'),
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='number',
            field=models.IntegerField(validators=[college.validators.validate_group_number]),
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup_curriculum',
            unique_together={('student_group', 'curriculum', 'teacher')},
        ),
    ]
