# Generated by Django 3.2.9 on 2022-03-24 21:08

import college.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220321_1619'),
        ('college', '0002_auto_20220214_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'verbose_name': 'Curriculum', 'verbose_name_plural': 'Curriculums'},
        ),
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Speciality', 'verbose_name_plural': 'Specialities'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'verbose_name': 'StudentGroup', 'verbose_name_plural': 'StudentGroups'},
        ),
        migrations.AlterModelOptions(
            name='studentgroup_curriculum',
            options={'verbose_name': 'StudentGroup_Curriculum', 'verbose_name_plural': 'StudentGroup_Curriculums'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': 'Year', 'verbose_name_plural': 'Years'},
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='college.subject', verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='college.year', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='abbreviation',
            field=models.CharField(max_length=6, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='group_prefix',
            field=models.CharField(max_length=3, verbose_name='group_prefix'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='facilitator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_group', to='users.teacher', verbose_name='facilitator'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='number',
            field=models.IntegerField(validators=[college.validators.validate_group_number], verbose_name='number'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='subjects',
            field=models.ManyToManyField(related_name='student_groups', through='college.StudentGroup_Curriculum', to='college.Curriculum', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='title',
            field=models.CharField(max_length=10, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.year', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='studentgroup_curriculum',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.curriculum', verbose_name='curriculum'),
        ),
        migrations.AlterField(
            model_name='studentgroup_curriculum',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.studentgroup', verbose_name='student_group'),
        ),
        migrations.AlterField(
            model_name='studentgroup_curriculum',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacher', verbose_name='teacher'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='abbreviation',
            field=models.CharField(max_length=10, unique=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='year',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='years', to='college.speciality', verbose_name='speciality'),
        ),
        migrations.AlterField(
            model_name='year',
            name='start_year',
            field=models.IntegerField(validators=[college.validators.validate_start_year], verbose_name='start_year'),
        ),
        migrations.AlterField(
            model_name='year',
            name='subjects',
            field=models.ManyToManyField(through='college.Curriculum', to='college.Subject', verbose_name='subjects'),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year'), (4, 'Fourth year')], verbose_name='year'),
        ),
    ]
