# Generated by Django 3.2.9 on 2022-02-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_auto_20220222_1728'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='articles',
            field=models.ManyToManyField(to='wiki.Article'),
        ),
    ]
